### ISSUE TITLE
[BUG] executeQuery: variable "performance" not taken from the injected params

### ISSUE THREAD

**Issue by cristianizzo** [bh2smith/ts-dune-client#49]
login is wrong, performance will always be Medium...
https://github.com/bh2smith/ts-dune-client/blob/ad2040475ddf8593c529ab0da845ff727936a661/src/api/execution.ts#L47

**Comment by bh2smith** [comment]
Released with https://github.com/bh2smith/ts-dune-client/releases/tag/v0.1.5
